name: Stanziliëri
favicon: null
layout_spectrum: 0.30865072016604245
typography_spectrum: 0.042812146712094545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.18697979347780347
  lightness: 0.44061056384816766
  saturation: 0.09087826311588287
  rhythmicContrast: 0.5188942886888981
purpose: []
