name: Stanziliëri
favicon: null
layout_spectrum: 0.24758
typography_spectrum: 0.07335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededed'
    - '#4b4a4f'
    - '#7a797e'
    - '#28282a'
    - '#e9ab96'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
